stages:
- stage1

variables:
  REGISTRY: "dockerhub.atl01.norwexops.com"
  IMAGE_NAME: "jupyter-ruby"
  REPOSITORY: "$REGISTRY/$IMAGE_NAME"

before_script:
- mkdir -pv ~/.docker
- echo $DOCKER_CONFIG_BASE64 | base64 -d > ~/.docker/config.json
- echo $SSH_PRIVATE_KEY_BASE64 | base64 -d > ./stelladeploy_rsa

publish-tag:
  image: 'docker:20.10.12'
  stage: stage1
  variables:
    DOCKER_IMAGE_TAG: "$CI_COMMIT_TAG"
  only:
  - tags
  script:
  - docker build -t $REPOSITORY:$DOCKER_IMAGE_TAG .
  - docker tag $REPOSITORY:$DOCKER_IMAGE_TAG $REPOSITORY:latest
  - docker push $REPOSITORY:$DOCKER_IMAGE_TAG
  - docker push $REPOSITORY:latest
  - docker rmi $REPOSITORY:$DOCKER_IMAGE_TAG
  - docker rmi $REPOSITORY:latest

publish-branch:
  image: 'docker:20.10.12'
  stage: stage1
  variables:
    DOCKER_IMAGE_TAG: "$CI_COMMIT_REF_SLUG"
  only:
  - branches
  script:
  - docker build -t $REPOSITORY:$DOCKER_IMAGE_TAG .
  - docker push $REPOSITORY:$DOCKER_IMAGE_TAG
  - docker rmi $REPOSITORY:$DOCKER_IMAGE_TAG

